SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."managers" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       text                     NOT NULL,
  "is_active"  boolean                  NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "managers_name_key" UNIQUE (name),
  CONSTRAINT "managers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."managers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."matches" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "played_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "season_id"      bigint                   NOT NULL,
  "manager_id"     bigint                   NOT NULL,
  "opponent_id"    bigint                   NOT NULL,
  "our_goals"      integer                  NOT NULL,
  "opponent_goals" integer                  NOT NULL,
  "location"       text,
  "notes"          text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "matches_location_check" CHECK ((location = ANY (ARRAY['home'::text, 'away'::text]))),
  CONSTRAINT "matches_opponent_goals_check" CHECK ((opponent_goals >= 0)),
  CONSTRAINT "matches_our_goals_check" CHECK ((our_goals >= 0)),
  CONSTRAINT "matches_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."matches"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."opponents" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "opponents_name_key" UNIQUE (name),
  CONSTRAINT "opponents_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."opponents"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"         uuid                     NOT NULL,
  "email"      text                     NOT NULL,
  "role"       text                     NOT NULL DEFAULT 'user'::text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text])))
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."seasons" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       text                     NOT NULL,
  "start_date" date,
  "end_date"   date,
  "is_active"  boolean                  NOT NULL DEFAULT false,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "seasons_name_key" UNIQUE (name),
  CONSTRAINT "seasons_pkey" PRIMARY KEY (id),
  CONSTRAINT "seasons_valid_date_range" CHECK (((end_date IS NULL) OR (start_date IS NULL) OR (end_date >= start_date)))
);

ALTER TABLE "public"."seasons"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

ALTER TABLE "public"."matches"
  ADD CONSTRAINT "matches_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.managers(id);

ALTER TABLE "public"."matches"
  ADD CONSTRAINT "matches_opponent_id_fkey" FOREIGN KEY (opponent_id) REFERENCES public.opponents(id);

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."matches"
  ADD CONSTRAINT "matches_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id);

CREATE INDEX matches_manager_id_idx ON public.matches USING btree (manager_id);

CREATE INDEX matches_opponent_id_idx ON public.matches USING btree (opponent_id);

CREATE INDEX matches_season_id_idx ON public.matches USING btree (season_id);

CREATE UNIQUE INDEX seasons_only_one_active_idx ON public.seasons USING btree (is_active)
  WHERE (is_active = true);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "Admins can manage managers" ON "public"."managers"
  FOR ALL
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Authenticated users can read managers" ON "public"."managers"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Require MFA" ON "public"."managers"
  AS RESTRICTIVE
  FOR ALL
  TO "authenticated"
  USING ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text))
  WITH CHECK ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text));

CREATE POLICY "Admins can manage matches" ON "public"."matches"
  FOR ALL
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Authenticated users can read matches" ON "public"."matches"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Require MFA" ON "public"."matches"
  AS RESTRICTIVE
  FOR ALL
  TO "authenticated"
  USING ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text))
  WITH CHECK ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text));

CREATE POLICY "Admins can manage opponents" ON "public"."opponents"
  FOR ALL
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Authenticated users can read opponents" ON "public"."opponents"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Require MFA" ON "public"."opponents"
  AS RESTRICTIVE
  FOR ALL
  TO "authenticated"
  USING ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text))
  WITH CHECK ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text));

CREATE POLICY "Admins can manage profiles" ON "public"."profiles"
  FOR ALL
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Require MFA" ON "public"."profiles"
  AS RESTRICTIVE
  FOR ALL
  TO "authenticated"
  USING ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text))
  WITH CHECK ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text));

CREATE POLICY "Users can read own profile" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Admins can manage seasons" ON "public"."seasons"
  FOR ALL
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Authenticated users can read seasons" ON "public"."seasons"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Require MFA" ON "public"."seasons"
  AS RESTRICTIVE
  FOR ALL
  TO "authenticated"
  USING ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text))
  WITH CHECK ((( SELECT (auth.jwt() ->> 'aal'::text)) = 'aal2'::text));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."is_admin"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "authenticated", "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."managers" TO "anon";

REVOKE ALL ON TABLE "public"."managers" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, SELECT, UPDATE ON TABLE "public"."managers" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."managers" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."managers" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."matches" TO "anon";

REVOKE ALL ON TABLE "public"."matches" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, SELECT, UPDATE ON TABLE "public"."matches" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."matches" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."matches" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."opponents" TO "anon";

REVOKE ALL ON TABLE "public"."opponents" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, SELECT, UPDATE ON TABLE "public"."opponents" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."opponents" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."opponents" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "anon";

REVOKE ALL ON TABLE "public"."profiles" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, SELECT, UPDATE ON TABLE "public"."profiles" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."seasons" TO "anon";

REVOKE ALL ON TABLE "public"."seasons" FROM "authenticated";

GRANT DELETE, INSERT, MAINTAIN, SELECT, UPDATE ON TABLE "public"."seasons" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."seasons" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."seasons" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

