CREATE TABLE public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  owner_profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.team_members (
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (team_id, profile_id)
);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read team memberships" ON public.team_members
  FOR SELECT TO authenticated USING (profile_id = auth.uid());
CREATE POLICY "Users can read their teams" ON public.teams
  FOR SELECT TO authenticated USING (id IN (SELECT team_id FROM public.team_members WHERE profile_id = auth.uid()));

INSERT INTO public.teams (name, owner_profile_id)
SELECT 'Equipo Principal', id FROM public.profiles WHERE role = 'admin' LIMIT 1;

INSERT INTO public.team_members (team_id, profile_id)
SELECT teams.id, profiles.id FROM public.teams teams CROSS JOIN public.profiles
WHERE teams.name = 'Equipo Principal'
ON CONFLICT DO NOTHING;

ALTER TABLE public.managers ADD COLUMN team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.matches ADD COLUMN team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.opponents ADD COLUMN team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.seasons ADD COLUMN team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE;

UPDATE public.managers SET team_id = (SELECT id FROM public.teams WHERE name = 'Equipo Principal');
UPDATE public.matches SET team_id = (SELECT id FROM public.teams WHERE name = 'Equipo Principal');
UPDATE public.opponents SET team_id = (SELECT id FROM public.teams WHERE name = 'Equipo Principal');
UPDATE public.seasons SET team_id = (SELECT id FROM public.teams WHERE name = 'Equipo Principal');

ALTER TABLE public.managers ALTER COLUMN team_id SET NOT NULL;
ALTER TABLE public.matches ALTER COLUMN team_id SET NOT NULL;
ALTER TABLE public.opponents ALTER COLUMN team_id SET NOT NULL;
ALTER TABLE public.seasons ALTER COLUMN team_id SET NOT NULL;

ALTER TABLE public.managers DROP CONSTRAINT managers_name_key;
ALTER TABLE public.opponents DROP CONSTRAINT opponents_name_key;
ALTER TABLE public.seasons DROP CONSTRAINT seasons_name_key;
ALTER TABLE public.managers DROP CONSTRAINT managers_profile_id_key;
ALTER TABLE public.managers ADD CONSTRAINT managers_team_name_key UNIQUE (team_id, name);
ALTER TABLE public.opponents ADD CONSTRAINT opponents_team_name_key UNIQUE (team_id, name);
ALTER TABLE public.seasons ADD CONSTRAINT seasons_team_name_key UNIQUE (team_id, name);
ALTER TABLE public.managers ADD CONSTRAINT managers_team_profile_key UNIQUE (team_id, profile_id);

CREATE INDEX matches_team_id_idx ON public.matches(team_id);
CREATE INDEX managers_team_id_idx ON public.managers(team_id);
CREATE INDEX opponents_team_id_idx ON public.opponents(team_id);
CREATE INDEX seasons_team_id_idx ON public.seasons(team_id);

CREATE OR REPLACE FUNCTION public.set_profile_display_name(p_display_name text)
  RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE clean_display_name text := btrim(p_display_name);
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Unauthorized'; END IF;
  IF clean_display_name IS NULL OR char_length(clean_display_name) NOT BETWEEN 1 AND 50 THEN RAISE EXCEPTION 'Display name must contain between 1 and 50 characters'; END IF;
  UPDATE public.profiles SET display_name = clean_display_name WHERE id = auth.uid();
  INSERT INTO public.managers (name, profile_id, team_id)
  SELECT clean_display_name, auth.uid(), team_id FROM public.team_members WHERE profile_id = auth.uid()
  ON CONFLICT (team_id, profile_id) DO UPDATE SET name = EXCLUDED.name;
END;
$function$;
